version: '3'

services:
  pqai_db:
    image: pqai_db
    container_name: pqai_db
    build: .
    restart: always
    ports:
      - ${PORT}:80
    environment:
      - PORT=${PORT}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLL=${MONGO_COLL}
      - STORAGE=${STORAGE}
